import { useState, useRef, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { Session } from '../lib/session'
import { SPECIALTIES, CITIES, AREAS } from '../lib/constants'

const C = {
  primary: '#1A5C2A', gold: '#F9A825', white: '#fff',
  bg: '#F8F9FA', textSec: '#6B7280', error: '#D32F2F',
  errorBg: '#FFEBEE', border: '#E5E7EB', surface: '#E8F5E9',
}

function cleanPhone(raw: string) {
  return raw.replace(/[\s\-]/g, '').replace(/^(\+?00255|\+?255|0)/, '')
}

type Step = 'personal' | 'work' | 'otp' | 'nida' | 'success'

export default function WingaRegisterScreen() {
  const nav = useNavigate()
  const [step, setStep] = useState<Step>('personal')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  // Personal info
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [phone, setPhone] = useState('')
  const [email, setEmail] = useState('')

  // Work info
  const [specialty, setSpecialty] = useState('')
  const [city, setCity] = useState('Dar es Salaam')
  const [area, setArea] = useState('Kariakoo')
  const [bio, setBio] = useState('')

  // NIDA
  const [nidaNumber, setNidaNumber] = useState('')

  // OTP
  const [otp, setOtp] = useState(['', '', '', '', '', ''])
  const [countdown, setCountdown] = useState(0)
  const [resending, setResending] = useState(false)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const mountedRef = useRef(true)

  // Success
  const [assignedWingaId, setAssignedWingaId] = useState('')

  useEffect(() => () => {
    mountedRef.current = false
    if (timerRef.current) clearInterval(timerRef.current)
  }, [])

  const clean = cleanPhone(phone)
  const step1Valid = firstName.trim() && lastName.trim() && clean.length >= 9
  const step2Valid = specialty && city && area
  const stepNidaValid = nidaNumber.trim().length >= 8

  const stepNum = step === 'personal' ? 1 : step === 'work' ? 2 : step === 'otp' ? 3 : step === 'nida' ? 4 : 4
  const stepLabel = {
    personal: 'Hatua 1 / 4 — Taarifa Zako',
    work: 'Hatua 2 / 4 — Kazi Yako',
    otp: 'Hatua 3 / 4 — Thibitisha Simu',
    nida: 'Hatua 4 / 4 — NIDA na Kumaliza',
    success: 'Imefanikiwa!',
  }

  const startCountdown = (s = 60) => {
    if (timerRef.current) clearInterval(timerRef.current)
    setCountdown(s)
    let c = s
    timerRef.current = setInterval(() => {
      c--
      if (!mountedRef.current) { clearInterval(timerRef.current!); return }
      setCountdown(c)
      if (c <= 0) clearInterval(timerRef.current!)
    }, 1000)
  }

  const sendOtp = async (isResend = false) => {
    if (isResend) setResending(true)
    else setLoading(true)
    setError('')
    try {
      const { error: e } = await supabase.auth.signInWithOtp({ phone: `+255${clean}` })
      if (e) throw e
      if (!mountedRef.current) return
      if (!isResend) setStep('otp')
      startCountdown()
    } catch (e: any) {
      if (mountedRef.current) setError(e.message || 'Hitilafu imetokea')
    } finally {
      if (mountedRef.current) { setLoading(false); setResending(false) }
    }
  }

  const verify = async () => {
    const code = otp.join('')
    if (code.length < 6) return
    setLoading(true); setError('')
    try {
      const { data, error: e } = await supabase.auth.verifyOtp({
        phone: `+255${clean}`, token: code, type: 'sms',
      })
      if (e) throw e
      const uid = data.user?.id
      if (!uid) throw new Error('Uthibitisho umeshindwa')

      const fullName = `${firstName.trim()} ${lastName.trim()}`

      // 1. Create/update user record
      await supabase.from('users').upsert({
        id: uid,
        phone: `+255${clean}`,
        email: email.trim() || null,
        name: fullName,
        user_type: 'winga',
        is_verified: true,
      }, { onConflict: 'id' })

      // 2. Create winga record — winga_id auto-generated by DB trigger
      //    profile_complete = false, is_online = false (default)
      const { data: wingaData, error: wingaErr } = await supabase.from('wingas').insert({
        user_id: uid,
        name: fullName,
        phone: `+255${clean}`,
        email: email.trim() || null,
        specialty,
        home_location: `${area}, ${city}`,
        current_city: city,
        current_area: area,
        bio: bio.trim() || null,
        status: 'pending',
        verification_status: 'verified',
        badge: 'Starter',
        is_online: false,
        profile_complete: false,
      }).select('winga_id').single()

      if (wingaErr && !wingaErr.message.includes('duplicate')) throw wingaErr

      const wid = wingaData?.winga_id || ''

      if (!mountedRef.current) return
      setAssignedWingaId(wid)
      setStep('nida')
      setLoading(false)
    } catch (e: any) {
      if (!mountedRef.current) return
      setError(e.message?.includes('Invalid') ? 'Code si sahihi.' : e.message || 'Hitilafu')
      setLoading(false)
    }
  }

  const submitNida = async () => {
    if (!stepNidaValid) return
    setLoading(true); setError('')
    try {
      const { data: { user } } = await supabase.auth.getUser()
      const uid = user?.id || Session.uid()
      if (!uid) throw new Error('Haufikiki')

      // Save NIDA number
      const { error: nidaErr } = await supabase.from('wingas').update({
        national_id: nidaNumber.trim(),
      }).eq('user_id', uid)
      if (nidaErr) throw nidaErr

      // Check profile completion
      const { data: statusData } = await supabase.rpc('get_winga_profile_status', { p_user_id: uid })

      if (!mountedRef.current) return

      if (statusData?.profile_complete) {
        // All done — go to home
        await supabase.from('wingas').update({ is_online: false }).eq('user_id', uid)
        Session.set(uid, 'winga')
        setStep('success')
      } else {
        // Still need more fields — go to success screen showing what's missing
        Session.set(uid, 'winga')
        setStep('success')
      }
      setLoading(false)
    } catch (e: any) {
      if (!mountedRef.current) return
      setError(e.message || 'Hitilafu')
      setLoading(false)
    }
  }

  const handleOtpChange = (val: string, i: number) => {
    const digits = val.replace(/\D/g, '')
    if (digits.length > 1) {
      const next = [...otp]
      digits.split('').forEach((d, j) => { if (i + j < 6) next[i + j] = d })
      setOtp(next)
      const filled = next.join('').length
      if (filled === 6) setTimeout(verify, 100)
      return
    }
    const next = [...otp]; next[i] = digits; setOtp(next)
    if (digits && i < 5) (document.getElementById(`wotp-${i + 1}`) as HTMLInputElement)?.focus()
    else if (!digits && i > 0) (document.getElementById(`wotp-${i - 1}`) as HTMLInputElement)?.focus()
    if (next.join('').length === 6) setTimeout(verify, 100)
  }

  return (
    <div style={{ height: '100dvh', display: 'flex', flexDirection: 'column', background: C.white, overflowY: 'hidden' }}>
      {/* Header */}
      <div style={{ background: C.primary, paddingTop: 'calc(env(safe-area-inset-top,0px) + 16px)', paddingBottom: 20, paddingLeft: 20, paddingRight: 20, flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
          <button onClick={() => {
            if (step === 'personal') nav('/login')
            else if (step === 'work') setStep('personal')
            else if (step === 'otp') setStep('work')
            else if (step === 'nida') setStep('otp')
          }}
            style={{ background: 'none', border: 'none', color: C.white, fontSize: 22, cursor: 'pointer', padding: 0 }}>←</button>
          <div>
            <div style={{ fontFamily: 'Inter', fontSize: 18, fontWeight: 700, color: C.white }}>Jiunge kama Winga</div>
            <div style={{ fontFamily: 'Inter', fontSize: 12, color: 'rgba(255,255,255,0.75)' }}>
              {stepLabel[step]}
            </div>
          </div>
        </div>
        {/* Progress bar */}
        <div style={{ height: 4, background: 'rgba(255,255,255,0.2)', borderRadius: 2 }}>
          <div style={{ height: '100%', background: C.gold, borderRadius: 2, width: `${(stepNum / 4) * 100}%`, transition: 'width 0.3s ease' }} />
        </div>
      </div>

      <div style={{ flex: 1, overflowY: 'auto', WebkitOverflowScrolling: 'touch', padding: '20px 20px 0' }}>
        {error && (
          <div style={{ background: C.errorBg, color: C.error, padding: '12px 16px', borderRadius: 12, marginBottom: 16, fontFamily: 'Inter', fontSize: 13, display: 'flex', gap: 8 }}>
            ⚠️ {error}
          </div>
        )}

        {/* ── STEP 1: Personal ── */}
        {step === 'personal' && (
          <>
            <div style={{ background: C.surface, borderRadius: 14, padding: '14px 16px', marginBottom: 20 }}>
              <div style={{ fontFamily: 'Inter', fontSize: 22, marginBottom: 4 }}>👤</div>
              <div style={{ fontFamily: 'Inter', fontSize: 14, fontWeight: 700, color: C.primary }}>Taarifa za Kibinafsi</div>
              <div style={{ fontFamily: 'Inter', fontSize: 12, color: C.textSec }}>Jina lako kamili litaonekana kwa wateja</div>
            </div>
            {[
              { label: 'Jina la Kwanza *', val: firstName, set: setFirstName, placeholder: 'Ahmed', type: 'text' },
              { label: 'Jina la Mwisho *', val: lastName, set: setLastName, placeholder: 'Juma', type: 'text' },
            ].map(f => <Field key={f.label} {...f} />)}
            <div style={{ marginBottom: 14 }}>
              <label style={labelStyle}>Namba ya Simu *</label>
              <div style={{ display: 'flex', gap: 8 }}>
                <div style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: 12, padding: '14px 12px', fontFamily: 'Inter', fontWeight: 600, fontSize: 14, color: C.primary, whiteSpace: 'nowrap' }}>🇹🇿 +255</div>
                <input value={phone} onChange={e => setPhone(e.target.value)} type="tel" placeholder="712 345 678" style={inputStyle(C)} />
              </div>
            </div>
            <Field label="Barua Pepe (hiari)" val={email} set={setEmail} placeholder="ahmed@example.com" type="email" />
            <div style={{ height: 16 }} />
            <Btn label="Endelea →" onClick={() => { setError(''); setStep('work') }} disabled={!step1Valid} loading={false} />
          </>
        )}

        {/* ── STEP 2: Work ── */}
        {step === 'work' && (
          <>
            <div style={{ background: C.surface, borderRadius: 14, padding: '14px 16px', marginBottom: 20 }}>
              <div style={{ fontFamily: 'Inter', fontSize: 22, marginBottom: 4 }}>🛍️</div>
              <div style={{ fontFamily: 'Inter', fontSize: 14, fontWeight: 700, color: C.primary }}>Kazi yako na Eneo</div>
              <div style={{ fontFamily: 'Inter', fontSize: 12, color: C.textSec }}>Wateja watakupata kulingana na taarifa hizi</div>
            </div>

            <div style={{ marginBottom: 14 }}>
              <label style={labelStyle}>Utaalamu Wako *</label>
              <select value={specialty} onChange={e => setSpecialty(e.target.value)} style={{ ...inputStyle(C), width: '100%' }}>
                <option value="">Chagua utaalamu...</option>
                {SPECIALTIES.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>

            <div style={{ marginBottom: 14 }}>
              <label style={labelStyle}>Mji / Jiji *</label>
              <select value={city} onChange={e => { setCity(e.target.value); setArea(AREAS[e.target.value]?.[0] || '') }} style={{ ...inputStyle(C), width: '100%' }}>
                {Object.keys(AREAS).map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>

            <div style={{ marginBottom: 14 }}>
              <label style={labelStyle}>Eneo / Mtaa *</label>
              <select value={area} onChange={e => setArea(e.target.value)} style={{ ...inputStyle(C), width: '100%' }}>
                {(AREAS[city] || []).map(a => <option key={a} value={a}>{a}</option>)}
              </select>
            </div>

            <div style={{ marginBottom: 14 }}>
              <label style={labelStyle}>Jielezeshe (hiari)</label>
              <textarea value={bio} onChange={e => setBio(e.target.value)} rows={3} maxLength={200}
                placeholder="Ninafahamu Kariakoo vizuri sana, nimefanya kazi zaidi ya miaka 5..."
                style={{ ...inputStyle(C), width: '100%', resize: 'none', fontFamily: 'Inter' }} />
            </div>

            {/* Tier info */}
            <div style={{ border: `1px solid ${C.border}`, borderRadius: 14, padding: 16, marginBottom: 20 }}>
              <div style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: 700, marginBottom: 10, color: C.primary }}>📊 Mfumo wa Ubora wa Winga</div>
              {[
                { badge: '🥉', name: 'Starter', desc: 'Unaanza mara moja — bure', color: '#FFF3E0', border: '#CD7F32' },
                { badge: '🥈', name: 'Mid', desc: '10+ safari + score 60%', color: '#F5F5F5', border: '#9E9E9E' },
                { badge: '🥇', name: 'Verified', desc: '30+ safari + score 80%', color: '#FFF8E1', border: '#F9A825' },
              ].map(t => (
                <div key={t.name} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '8px 0', borderBottom: t.name !== 'Verified' ? `1px solid ${C.border}` : 'none' }}>
                  <span style={{ fontSize: 20 }}>{t.badge}</span>
                  <div>
                    <div style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: 600 }}>{t.name}</div>
                    <div style={{ fontFamily: 'Inter', fontSize: 11, color: C.textSec }}>{t.desc}</div>
                  </div>
                </div>
              ))}
              <div style={{ marginTop: 10, background: C.surface, borderRadius: 10, padding: 10 }}>
                <div style={{ fontFamily: 'Inter', fontSize: 11, color: C.primary }}>
                  ✅ Utaanza na badge ya Starter mara moja bila malipo. Badge inaboreshwa kiotomatiki kulingana na alama za wateja.
                </div>
              </div>
            </div>
            <Btn label="Endelea — Thibitisha Simu →" onClick={() => { setError(''); sendOtp(false) }} disabled={!step2Valid} loading={loading} />
          </>
        )}

        {/* ── STEP 3: OTP ── */}
        {step === 'otp' && (
          <>
            <div style={{ textAlign: 'center', padding: '20px 0 24px' }}>
              <div style={{ fontSize: 52, marginBottom: 12 }}>📱</div>
              <div style={{ fontFamily: 'Inter', fontSize: 20, fontWeight: 700, marginBottom: 6 }}>Thibitisha Namba Yako</div>
              <div style={{ fontFamily: 'Inter', fontSize: 13, color: C.textSec }}>
                Tumetuma SMS kwenda <strong style={{ color: C.primary }}>+255 {phone}</strong>
              </div>
            </div>
            <div style={{ display: 'flex', gap: 8, justifyContent: 'center', marginBottom: 20 }}>
              {otp.map((v, i) => (
                <input key={i} id={`wotp-${i}`} value={v} type="tel" inputMode="numeric" maxLength={6}
                  onChange={e => handleOtpChange(e.target.value, i)}
                  onKeyDown={e => { if (e.key === 'Backspace' && !v && i > 0) (document.getElementById(`wotp-${i - 1}`) as HTMLInputElement)?.focus() }}
                  style={{ width: 48, height: 58, textAlign: 'center', fontSize: 22, fontWeight: 700, fontFamily: 'Inter', border: `2px solid ${v ? C.primary : C.border}`, borderRadius: 12, outline: 'none', background: v ? C.surface : C.white, transition: 'all 0.15s' }} />
              ))}
            </div>
            <div style={{ textAlign: 'center', marginBottom: 20 }}>
              {countdown > 0
                ? <span style={{ fontFamily: 'Inter', fontSize: 13, color: C.textSec }}>Tuma tena baada ya 00:{String(countdown).padStart(2, '0')}</span>
                : <button onClick={() => sendOtp(true)} disabled={resending}
                  style={{ background: 'none', border: 'none', color: C.primary, fontWeight: 600, cursor: 'pointer', fontFamily: 'Inter', fontSize: 13 }}>
                  {resending ? '⏳ Inatuma...' : '🔄 Tuma Code Tena'}
                </button>}
            </div>
            <Btn label="Thibitisha na Endelea →" onClick={verify} disabled={otp.join('').length < 6} loading={loading} />
            <div style={{ background: C.surface, borderRadius: 12, padding: 12, marginTop: 16 }}>
              <div style={{ fontFamily: 'Inter', fontSize: 12, color: C.primary }}>🔒 Kamwe usishirikishe code hii na mtu yeyote.</div>
            </div>
          </>
        )}

        {/* ── STEP 4: NIDA + Complete Profile ── */}
        {step === 'nida' && (
          <>
            {/* Winga ID Card */}
            <div style={{ background: `linear-gradient(135deg, ${C.primary}, #2E7D32)`, borderRadius: 16, padding: '20px', marginBottom: 24, textAlign: 'center' }}>
              <div style={{ fontFamily: 'Inter', fontSize: 11, color: 'rgba(255,255,255,0.7)', marginBottom: 4, letterSpacing: 2 }}>WINGA ID YAKO</div>
              <div style={{ fontFamily: 'Inter', fontSize: 28, fontWeight: 800, color: C.gold, letterSpacing: 3, marginBottom: 8 }}>
                {assignedWingaId || 'WNGA-'}
              </div>
              <div style={{ fontFamily: 'Inter', fontSize: 11, color: 'rgba(255,255,255,0.8)' }}>
                ✅ Imethibitishwa — Hifadhi ID hii kwa ajili ya login
              </div>
            </div>

            <div style={{ background: C.surface, borderRadius: 14, padding: '14px 16px', marginBottom: 20 }}>
              <div style={{ fontFamily: 'Inter', fontSize: 22, marginBottom: 4 }}>🪪</div>
              <div style={{ fontFamily: 'Inter', fontSize: 14, fontWeight: 700, color: C.primary }}>Namba ya NIDA *</div>
              <div style={{ fontFamily: 'Inter', fontSize: 12, color: C.textSec }}>Namba yako ya kitambulisho cha taifa (NIDA) inahitajika</div>
            </div>

            <div style={{ marginBottom: 14 }}>
              <label style={labelStyle}>Namba ya NIDA *</label>
              <input
                value={nidaNumber}
                onChange={e => setNidaNumber(e.target.value.replace(/\D/g, '').slice(0, 20))}
                type="tel"
                inputMode="numeric"
                placeholder="Mfano: 1234567890123"
                maxLength={20}
                style={{
                  ...inputStyle(C),
                  width: '100%',
                  fontSize: 18,
                  letterSpacing: 2,
                  fontWeight: 600,
                  fontFamily: 'monospace',
                }}
              />
              <div style={{ fontFamily: 'Inter', fontSize: 11, color: C.textSec, marginTop: 4 }}>
                {nidaNumber.length}/20 tarakimu
              </div>
            </div>

            <div style={{ background: '#FFF8E1', borderRadius: 12, padding: 14, marginBottom: 20, border: '1px solid #F9A825' }}>
              <div style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: 700, color: '#F57F17', marginBottom: 6 }}>
                ⚠️ Taarifa Muhimu
              </div>
              <div style={{ fontFamily: 'Inter', fontSize: 12, color: '#5D4037', lineHeight: 1.6 }}>
                Baada ya kusajili, utahitaji kumaliza wasifu wako 100% kabla ya kupokea maombi ya wateja.
                Wasifu unahitaji: Picha, Kuhusu Mimi, na taarifa zote kuzimika.
              </div>
            </div>

            <Btn
              label="Maliza Usajili ✅"
              onClick={submitNida}
              disabled={!stepNidaValid}
              loading={loading}
            />
          </>
        )}

        {/* ── SUCCESS SCREEN ── */}
        {step === 'success' && (
          <>
            <div style={{ textAlign: 'center', padding: '30px 0 20px' }}>
              <div style={{ fontSize: 64, marginBottom: 16 }}>🎉</div>
              <div style={{ fontFamily: 'Inter', fontSize: 24, fontWeight: 800, color: C.primary, marginBottom: 8 }}>
                Hongera, Winga!
              </div>
              <div style={{ fontFamily: 'Inter', fontSize: 14, color: C.textSec, marginBottom: 24 }}>
                Usajili wako umekamilika kwa mafanikio.
              </div>
            </div>

            {/* Winga ID Card */}
            <div style={{ background: `linear-gradient(135deg, ${C.primary}, #2E7D32)`, borderRadius: 16, padding: '20px', marginBottom: 24, textAlign: 'center' }}>
              <div style={{ fontFamily: 'Inter', fontSize: 11, color: 'rgba(255,255,255,0.7)', marginBottom: 4, letterSpacing: 2 }}>WINGA ID YAKO</div>
              <div style={{ fontFamily: 'Inter', fontSize: 32, fontWeight: 800, color: C.gold, letterSpacing: 3, marginBottom: 6 }}>
                {assignedWingaId || '—'}
              </div>
              <div style={{ fontFamily: 'Inter', fontSize: 12, color: 'rgba(255,255,255,0.9)' }}>
                {firstName} {lastName}
              </div>
            </div>

            {/* Login info */}
            <div style={{ background: C.surface, borderRadius: 14, padding: 16, marginBottom: 16 }}>
              <div style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: 700, color: C.primary, marginBottom: 10 }}>🔑 Jinsi ya Kuingia</div>
              {[
                { icon: '📱', label: 'Namba ya Simu', value: `+255 ${phone}` },
                { icon: '🪪', label: 'Winga ID', value: assignedWingaId },
              ].map(m => (
                <div key={m.label} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                  <span style={{ fontSize: 18 }}>{m.icon}</span>
                  <div>
                    <div style={{ fontFamily: 'Inter', fontSize: 11, color: C.textSec }}>{m.label}</div>
                    <div style={{ fontFamily: 'Inter', fontSize: 14, fontWeight: 600 }}>{m.value}</div>
                  </div>
                </div>
              ))}
            </div>

            {/* Profile completion reminder */}
            <div style={{ background: '#FFF8E1', borderRadius: 14, padding: 16, marginBottom: 24, border: '1px solid #F9A825' }}>
              <div style={{ fontFamily: 'Inter', fontSize: 13, fontWeight: 700, color: '#F57F17', marginBottom: 6 }}>
                📋 Maliza Wasifu Wako (100%)
              </div>
              <div style={{ fontFamily: 'Inter', fontSize: 12, color: '#5D4037', lineHeight: 1.6 }}>
                Ili kupokea maombi ya wateja, wasifu wako lazima uwe kamili 100%. Unahitaji kuongeza:
              </div>
              <div style={{ marginTop: 10 }}>
                {['📸 Picha ya Wasifu', '📝 Kuhusu Mimi (Bio)'].map(item => (
                  <div key={item} style={{ fontFamily: 'Inter', fontSize: 12, color: '#795548', padding: '4px 0' }}>
                    ⬜ {item}
                  </div>
                ))}
              </div>
              <div style={{ fontFamily: 'Inter', fontSize: 11, color: '#F57F17', marginTop: 8, fontStyle: 'italic' }}>
                Nenda kwenye Wasifu Wangu kumaliza.
              </div>
            </div>

            <Btn
              label="Enda kwenye Wasifu Wangu →"
              onClick={() => nav('/winga/profile', { replace: true })}
              disabled={false}
              loading={false}
            />
            <button
              onClick={() => nav('/winga/home', { replace: true })}
              style={{
                width: '100%', height: 48, marginTop: 10,
                background: 'none', border: `1.5px solid ${C.primary}`,
                borderRadius: 14, fontFamily: 'Inter', fontSize: 14,
                fontWeight: 600, color: C.primary, cursor: 'pointer',
              }}
            >
              Ruka — Nenda Home
            </button>
          </>
        )}
        <div style={{ height: 40 }} />
      </div>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  )
}

const labelStyle: React.CSSProperties = { fontFamily: 'Inter', fontSize: 13, fontWeight: 600, display: 'block', marginBottom: 6 }
const inputStyle = (C: any): React.CSSProperties => ({
  border: `1.5px solid ${C.border}`, borderRadius: 12, padding: '13px 14px',
  fontSize: 15, fontFamily: 'Inter', outline: 'none', background: C.white, boxSizing: 'border-box',
})
function Field({ label, val, set, placeholder, type = 'text' }: { label: string; val: string; set: (v: string) => void; placeholder: string; type?: string }) {
  const C = { border: '#E5E7EB', white: '#fff' }
  return (
    <div style={{ marginBottom: 14 }}>
      <label style={labelStyle}>{label}</label>
      <input value={val} onChange={e => set(e.target.value)} type={type} placeholder={placeholder} style={{ ...inputStyle(C), width: '100%' }} />
    </div>
  )
}
function Btn({ label, onClick, disabled, loading }: { label: string; onClick: () => void; disabled: boolean; loading: boolean }) {
  return (
    <button onClick={onClick} disabled={disabled || loading}
      style={{ width: '100%', height: 54, background: disabled ? '#9CA3AF' : '#1A5C2A', color: '#fff', border: 'none', borderRadius: 14, fontFamily: 'Inter', fontSize: 16, fontWeight: 600, cursor: disabled ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
      {loading ? <><span style={{ width: 18, height: 18, border: '2px solid rgba(255,255,255,0.4)', borderTop: '2px solid white', borderRadius: 9, display: 'inline-block', animation: 'spin 1s linear infinite' }} />Inaweka...</> : label}
    </button>
  )
}